language: python
python:
  - "3.6"
before_script:
  - "echo `curl -s https://pypi.org/pypi/tlds/json | jq -r .info.version || echo none` > /tmp/pkgver"
  - "curl -s https://data.iana.org/TLD/tlds-alpha-by-domain.txt | head -n 1 | grep -Po \"(?<=Version )[0-9]+\" > /tmp/dbver"
script: echo current=`cat /tmp/pkgver` iana=`cat /tmp/dbver`
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user:
    secure: "uMq/bESwfEEEqiF+KLF8j1N7jgZOmUCcj83UusPiSJbDm703qjSn8bZLXboPut9K3sgk5/Q6GKE06jE5Bsu3R+A/eEEHFmVBve4D5/HtVmDAODKlHjjVX5xU5cZZCd8Q68AlDuwoKCCW9z2FcahneXEA/kZBNX/4i7EboVZ35CjyjXe960FSkIBThxgrZAMaDWVbhhpzNzJEcKZZEoZenCMYgOWHWn25glckiNATUTCTnMxzsXOA5gwQkuv2dNcZ2OG9vJRHRsnspDPD6UWcg/16XZgDNoZ9VjI0etTcTKmi2t/VvUu5wUWhnKEytkkDbgip5CwqqU44BGfL1fGBZR3yWQlVvW8yoQ3+uWa9jUjSRelNxEenRM+129J+W6RQffZWrTPTFETKXIWcIOY5tWBWUicITAqqP20rINN0YRy7YziVFAObEbkfu1PJRXuiRsQmwvKvnKeGB+5W8UMF5K/oH+IVcDz211VkvkSPJJJkn/OGi+pGqmW1Ue53Zx1IOhJxsBQLj9kNGXZqgl/BdbViCKQ5ScoRh55z608mJY5wvINikJZGCT4hy5lpu/EyQnsIRTc9/CHH8hpE3Eon+RRgkv3/L7lHHEgAd8nu+SbjMNtLbriYD5kZAKfAWCe8XXB8bxTljY0kDcHwx4yeUzkzdkWpJj2XnCeZWIfx5hI="
  password:
    secure: "0b0B3rmRuYIQHu9CVb9I1q7s+Yo2RI3ezCl0t7s3umydSoctxGs5WorE/GNo4KZ2/eyISbmro22GRW0XNjTI4GcjOKb07LdA7Dh82gCcs6v3Aqe8086MW1vQvml64Y5ywxWgGrby+ncnzPOoUFSzvkdcMs0/2Q6ULGiOQ/Ub8OnWZeo00KAc15T53MxshKqIsK8278kwKiYrnbZmi8dzubcOzuuZN59ObCmNllfvfvpK8JrBzrYqMrMgU7xp8e4l0qfEp+qsL8jU/3uMGEOl/KLoqy8ltpZPbzU+1gCROpfYqlqQuqXydBUenIKea0vPqutgjlVFxf88URHVzJUTspshKcdyvAMRhCDQNhlFvjE7IfiT/ArmJkwP1k0tKgZ/Za+irqBp/qggrX9L2WXrVqBphOiBJLOmVBjQMWbiSxDdHzSxsX2r7dDBRlQyg6TU4WNpWvXnB9D43zwXxd/frzmDvpruRYtLCoHcBSldvg1LioE7KynZ+L2QCBouWEb6zu2FY2nRUeXQiib2c6fGESiIOI0J0aSLKb4k4Peu1aNiRpwk5KNNF6OKEQ33zz5kfLKuUkW6KEZdx0Nsx48+B627vnwYJp4bCQSSCjUI+SNmpFdcHe5khMEWSq9oHLx3ogzr1VumJOaQTrughbtAMBL59M5/S75w0JzMIN8eCSI="
  on:
    repo: kichik/tlds
    branch: master
    python: "3.6"
    condition: "`cat /tmp/pkgver` != `cat /tmp/dbver`"
addons:
  apt:
    packages:
      - curl
      - jq
