name: tlds build

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '10 5 * * *'

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          sudo apt install -y jq curl
      - name: Get latest domains
        id: get
        run: |
          set -ex
          echo "::set-output pkgver=`curl -s https://pypi.org/pypi/tlds/json | jq -r .info.version || echo none`"
          echo "::set-output dbver=`curl -s https://data.iana.org/TLD/tlds-alpha-by-domain.txt | head -n 1 | grep -Po \"(?<=Version )[0-9]+\"`"
      - name: Build a binary wheel and a source tarball
        if: ${{ steps.get.outputs.pkgver != steps.get.outputs.dbver }}
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        if: ${{ steps.get.outputs.pkgver != steps.get.outputs.dbver }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.pypi_user }}
          password: ${{ secrets.pypi_password }}