name: "Update"
on:
  workflow_dispatch:
  schedule: 
    - cron: "21 4 * * 0"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update top-level domains from iana
        run: ./update.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
